version: '3.7'

networks:
  favourites-network:
    external: true

services:
  arangodb_go_container:
    image: arangodb:latest
    container_name: arangodb_go_container
    environment:
      ARANGO_URL: http://arangodb_go_container:8529/_db/favourite/_api/database/current
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
    networks:
      - favourites-network

  favourite_assets_container:
    build: .
    image: favourite_assets
    container_name: favourite_assets_container 
    ports: 
      - 8000:8000
    depends_on:
      - arangodb_go_container
    networks:
      - favourites-network

volumes:
  arangodb_data_container:
  arangodb_apps_data_container: