// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"platform-go-challenge/domain"
	"sync"
)

type FakeFavouriteService struct {
	AddToFavouritesStub        func(string, string) (domain.Favourite, error)
	addToFavouritesMutex       sync.RWMutex
	addToFavouritesArgsForCall []struct {
		arg1 string
		arg2 string
	}
	addToFavouritesReturns struct {
		result1 domain.Favourite
		result2 error
	}
	addToFavouritesReturnsOnCall map[int]struct {
		result1 domain.Favourite
		result2 error
	}
	GetFavouritesStub        func(string) ([]domain.Asset, error)
	getFavouritesMutex       sync.RWMutex
	getFavouritesArgsForCall []struct {
		arg1 string
	}
	getFavouritesReturns struct {
		result1 []domain.Asset
		result2 error
	}
	getFavouritesReturnsOnCall map[int]struct {
		result1 []domain.Asset
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFavouriteService) AddToFavourites(arg1 string, arg2 string) (domain.Favourite, error) {
	fake.addToFavouritesMutex.Lock()
	ret, specificReturn := fake.addToFavouritesReturnsOnCall[len(fake.addToFavouritesArgsForCall)]
	fake.addToFavouritesArgsForCall = append(fake.addToFavouritesArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.AddToFavouritesStub
	fakeReturns := fake.addToFavouritesReturns
	fake.recordInvocation("AddToFavourites", []interface{}{arg1, arg2})
	fake.addToFavouritesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFavouriteService) AddToFavouritesCallCount() int {
	fake.addToFavouritesMutex.RLock()
	defer fake.addToFavouritesMutex.RUnlock()
	return len(fake.addToFavouritesArgsForCall)
}

func (fake *FakeFavouriteService) AddToFavouritesCalls(stub func(string, string) (domain.Favourite, error)) {
	fake.addToFavouritesMutex.Lock()
	defer fake.addToFavouritesMutex.Unlock()
	fake.AddToFavouritesStub = stub
}

func (fake *FakeFavouriteService) AddToFavouritesArgsForCall(i int) (string, string) {
	fake.addToFavouritesMutex.RLock()
	defer fake.addToFavouritesMutex.RUnlock()
	argsForCall := fake.addToFavouritesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFavouriteService) AddToFavouritesReturns(result1 domain.Favourite, result2 error) {
	fake.addToFavouritesMutex.Lock()
	defer fake.addToFavouritesMutex.Unlock()
	fake.AddToFavouritesStub = nil
	fake.addToFavouritesReturns = struct {
		result1 domain.Favourite
		result2 error
	}{result1, result2}
}

func (fake *FakeFavouriteService) AddToFavouritesReturnsOnCall(i int, result1 domain.Favourite, result2 error) {
	fake.addToFavouritesMutex.Lock()
	defer fake.addToFavouritesMutex.Unlock()
	fake.AddToFavouritesStub = nil
	if fake.addToFavouritesReturnsOnCall == nil {
		fake.addToFavouritesReturnsOnCall = make(map[int]struct {
			result1 domain.Favourite
			result2 error
		})
	}
	fake.addToFavouritesReturnsOnCall[i] = struct {
		result1 domain.Favourite
		result2 error
	}{result1, result2}
}

func (fake *FakeFavouriteService) GetFavourites(arg1 string) ([]domain.Asset, error) {
	fake.getFavouritesMutex.Lock()
	ret, specificReturn := fake.getFavouritesReturnsOnCall[len(fake.getFavouritesArgsForCall)]
	fake.getFavouritesArgsForCall = append(fake.getFavouritesArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetFavouritesStub
	fakeReturns := fake.getFavouritesReturns
	fake.recordInvocation("GetFavourites", []interface{}{arg1})
	fake.getFavouritesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFavouriteService) GetFavouritesCallCount() int {
	fake.getFavouritesMutex.RLock()
	defer fake.getFavouritesMutex.RUnlock()
	return len(fake.getFavouritesArgsForCall)
}

func (fake *FakeFavouriteService) GetFavouritesCalls(stub func(string) ([]domain.Asset, error)) {
	fake.getFavouritesMutex.Lock()
	defer fake.getFavouritesMutex.Unlock()
	fake.GetFavouritesStub = stub
}

func (fake *FakeFavouriteService) GetFavouritesArgsForCall(i int) string {
	fake.getFavouritesMutex.RLock()
	defer fake.getFavouritesMutex.RUnlock()
	argsForCall := fake.getFavouritesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFavouriteService) GetFavouritesReturns(result1 []domain.Asset, result2 error) {
	fake.getFavouritesMutex.Lock()
	defer fake.getFavouritesMutex.Unlock()
	fake.GetFavouritesStub = nil
	fake.getFavouritesReturns = struct {
		result1 []domain.Asset
		result2 error
	}{result1, result2}
}

func (fake *FakeFavouriteService) GetFavouritesReturnsOnCall(i int, result1 []domain.Asset, result2 error) {
	fake.getFavouritesMutex.Lock()
	defer fake.getFavouritesMutex.Unlock()
	fake.GetFavouritesStub = nil
	if fake.getFavouritesReturnsOnCall == nil {
		fake.getFavouritesReturnsOnCall = make(map[int]struct {
			result1 []domain.Asset
			result2 error
		})
	}
	fake.getFavouritesReturnsOnCall[i] = struct {
		result1 []domain.Asset
		result2 error
	}{result1, result2}
}

func (fake *FakeFavouriteService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addToFavouritesMutex.RLock()
	defer fake.addToFavouritesMutex.RUnlock()
	fake.getFavouritesMutex.RLock()
	defer fake.getFavouritesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFavouriteService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.FavouriteService = new(FakeFavouriteService)
